
# Experimento aleatorio y espacio muestral

{%youtube%}EnpAsENuryg{%endyoutube%}

Lanzar un dado y observar que numero aparece en la cara superior es lo que se denomina __experimento aleatorio__, ya que, si bien sabemos cuales son los posibles resultados (que salga 1 o 2 o 3 o 4 o 5 o 6 puntos), no podemos saber cual será el numero que saldrá en cada tirada particular. El conjunto de todos los posibles resultados se denomina __espacio muestral__ y se acostumbra a designar con la letra $\mathbf \Omega$.

> __Experimento aleatorio__ es aquel que tiene diferentes resultados posibles de los cuales no tenemos seguridad sobre que resultado se producirá realmente. Además, es indispensable que el experimento se pueda reproducir en condiciones idénticas tantas veces como sea necesario.


> __Espacio muestral__ es el conjunto de resultados posibles que podemos obtener en realizar un experimento aleatorio. Se designa por la letra $mathbf \Omega$.

##### Ejemplos de espacio muestral

En el caso del dado, el espacio muestral es:

$$\Omega =\left\{ 1,\quad 2,\quad 3,\quad 4,\quad 5,\quad 6 \right\}$$

Ver que saldrá si lanzamos una moneda al aire es un experimento aleatorio (los resultados posibles son cara o cruz, pero en cada tirada no podemos asegurar cual de los dos saldrá) con espacio muestral:

$$\Omega =\left\{ cara,\quad cruz \right\}$$

